server.servlet.context-path=/identity
spring.profiles.include=jms
spring.autoconfigure.exclude=io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/identity_service_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET:my-super-secret-key-that-is-at-least-256-bits-long!!}
jwt.expiration-ms=3600000