spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

queue.user.registered=${AWS_USER_REGISTERED_QUEUE:CHANGEIT}
queue.company.created=${AWS_COMPANY_CREATED_QUEUE:CHANGEIT}
queue.company.updated=${AWS_COMPANY_UPDATED_QUEUE:CHANGEIT}