spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

queue.job.applied=${AWS_JOB_APPLIED_QUEUE:CHANGEIT}
queue.company.updated=${AWS_COMPANY_UPDATED_QUEUE:CHANGEIT}
queue.application.status.out=${AWS_APPLICATION_STATUS_QUEUE:CHANGEIT}