spring.application.name=candidate-service
server.port=${SERVER_PORT:8081}
server.servlet.context-path=/candidate
spring.profiles.include=jms
spring.autoconfigure.exclude=io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/candidate_service_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false