spring.cloud.aws.region.static=ap-southeast-1
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:}

queue.job.applied=${AWS_JOB_APPLIED_QUEUE:CHANGEIT}
queue.user.registered=${AWS_USER_REGISTERED_QUEUE:CHANGEIT}
queue.application.status-changed=${AWS_APPLICATION_STATUS_CHANGED_QUEUE:CHANGEIT}